### ISSUE TITLE
Mythic Spell Focus

### ISSUE THREAD

**Issue by Hanhula** [dmrickey/ckl-foundry-modules#2]
Requesting mythic spell focus support ♥

> Benefit: Choose a school of magic you already have [Spell Focus](https://www.d20pfsrd.com/feats/general-feats/spell-focus) in. The bonus to save DCs provided by [Spell Focus](https://www.d20pfsrd.com/feats/general-feats/spell-focus) and [Greater Spell Focus](https://www.d20pfsrd.com/feats/general-feats/greater-spell-focus) for that school increases by 1. You can expend one use of mythic power as part of casting a spell from your chosen school to force any of the spell’s targets to roll their saving throws twice, taking the lower result.
> 
> Special: You can gain this feat multiple times. The effects do not stack. Each time you take this feat, it applies to a different non-mythic [Spell Focus](https://www.d20pfsrd.com/feats/general-feats/spell-focus) feat.

So from an implementation standpoint, there are two options I can see:

1. If Mythic Spell Focus is present, raise boost by SF and GSF by 1
2. Additional dropdowns on Spell Focus (Mythic) (to be selected if you only have Spell Focus) and Spell Focus (Mythic, Greater) (to be selected if you have both SF & GSF). These each add 1 to the total boost.

1 is nicer, 2 is easier (but I suppose would add an extra 'feat?'), either should work.

**Comment by dmrickey** [comment]
I didn't realize Mythic Spell Focus was a thing. I'll try to work on that this weekend. It should be pretty easy. 

Off the top of my head, my plan is to add a dropdown on the Mythic Feat (like I've added to spell focus/greater spell focus) but limit its choices to only those that you've already chosen for Spell Focus (and re-reading GSF it looks like I need to also add that limitation in there). I believe that's basically your option `#2`. 

`#1` doesn't seem like a good choice because it looks like the Mythic feat still requires you to make a choice. Unless I'm misunderstanding you, `#1` would make it so that if you have Spell Focus for three different schools, Mythic Spell Focus would automatically an extra +1 for each, where it should only be for one.

**Comment by Hanhula** [comment]
That'd pretty much be my option `#2`, yeah. It'll just need  to be able to also check for the presence of GSF as well, because the bonus will be +2 if you've got both.

Definitely see the issue with `#1`! 

As an aside, do you think you'd be interested in trying to develop the same for Elemental Focus? That one seems a bit more challenging.

**Comment by dmrickey** [comment]
I've got `#2` implemented but haven't had a chance to test it yet. And yes, it also accounts for GSF

Elemental focus looks like it should only be slightly more complicated than spell focus. I'll see if I can get that implemented, too

**Comment by dmrickey** [comment]
I've got a branch that has both mythic spell focus and also Elemental Focus changes in it now. I haven't had a chance at all to test it yet, but I plan on doing that tonight

**Comment by dmrickey** [comment]
@Hanhula This is now released in 1.3.0. If you have any other ideas or issues please let me know. Feel free to write up a new issue (or reopen this one if it's broken, lol). Though please also ping me on discord as I will definitely see that before I notice an issue here.
